__title__ = "dhashpy"
__description__ = "Row-wise gradient dHash algorithm implementation in python."
__url__ = "https://akamhy.github.io/dhashpy/"
__version__ = "1.0.0"
__author__ = "Akash Mahanty"
__author_email__ = "akamhy@yahoo.com"
__license__ = "MIT"
__copyright__ = "Copyright 2021 Akash Mahanty"
